### ISSUE TITLE
Uncapped memory growth

### ISSUE THREAD

**Issue by panicbit** [chridou/metrix#15]
Metrix seems to hoard tons of memory somehow without ever freeing it.
Affected version: 0.15 / 0b19e09
Steps to reproduce:
1. run `cargo run --example demo_run`
2. observe the processes memory increasing rapidly
3. wait a few more seconds and it OOMs

**Comment by panicbit** [comment]
![image](https://user-images.githubusercontent.com/628445/72186545-d3b3c700-33f5-11ea-8715-db04c4ba6eef.png)

**Comment by panicbit** [comment]
The reason for this seems to be a `TelemetryTransmitter`'s unbounded channel filling up due to the reading end not being able to keep up.
Making the channel bounded and using `try_send` "fixes" this, but discards observations if the channel fills up.

**Comment by chridou** [comment]
The `TelemetryTransmitter`s receiving part got some documentation to inform the user that it needs to be mounted on a `TelemetryDriver` to prevent this:

https://github.com/chridou/metrix/blob/cda429c5481727d2dd2db9e0e2a2c877f7b7dc36/src/lib.rs#L284-L289

https://github.com/chridou/metrix/blob/cda429c5481727d2dd2db9e0e2a2c877f7b7dc36/src/processor.rs#L205-L213

https://github.com/chridou/metrix/blob/cda429c5481727d2dd2db9e0e2a2c877f7b7dc36/src/processor.rs#L173-L181

**Comment by panicbit** [comment]
:+1:
